### ISSUE TITLE
Sign up for Google Analytics 

### ISSUE THREAD

**Issue by samjamead** [shouldibuildit/shouldibuildit.github.io#1]
Get a Google Analytics account and send Sam the tracking code snippet in Slack.

**Comment by camsinclair** [comment]
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-67992346-1', 'auto');
  ga('send', 'pageview');

</script>

**Comment by camsinclair** [comment]
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-67992346-1', 'auto');
  ga('send', 'pageview');

</script>

**Comment by samjamead** [comment]
Cam nailed it
