### ISSUE TITLE
Setup social media card in page's metadata

### ISSUE THREAD

**Issue by camsinclair** [shouldibuildit/shouldibuildit.github.io#10]
Refer to https://dev.twitter.com/cards/overview

**Comment by camsinclair** [comment]
![sibi-twitter-card](https://cloud.githubusercontent.com/assets/14801953/10069391/9f345720-62de-11e5-9198-8d35d89386a6.jpg)

**Comment by samjamead** [comment]
Closed by 21dc6d65cdfe825cfafe28e9fe5b2d9375f70430
