### ISSUE TITLE
Think about allowing longer responses to certain fields.

### ISSUE THREAD

**Issue by samjamead** [shouldibuildit/shouldibuildit.github.io#7]

**Comment by samjamead** [comment]
Currently, some fields cut the user off before they are finished going into all the detail. This could be a positive or a negative

**Comment by camsinclair** [comment]
I'm thinking keep each answer to 140 chars? If it's not worth saying in a tweet it's not worth saying etc?
Exceptions could be the team introductions.

**Comment by samjamead** [comment]
Deal
